name: Email Identifier Workflow

on:
  # Trigger on push to any branch
  push:
    branches:
      - '*'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  identify:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: 23f2005593@ds.study.iitm.ac.in
        run: |
          echo "This step identifies the workflow creator"
          echo "Running basic system checks..."
          date
          pwd
          ls -la
      
      - name: Run additional checks
        run: |
          echo "System information:"
          uname -a
          echo "Available disk space:"
          df -h
